### Ravikiran S B


In [1]:
#https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy

In [2]:
#Question 1 Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    modi_arr=numpy.array(arr).astype(float)
    modi_arr2=modi_arr[::-1]
    return modi_arr2


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [3]:
#Question 2 Shape and Reshape
import numpy

arr=list(map(int,input().split(' ')))
modi_arr=numpy.array(arr)
#modi_arr.shape(3,3)
print(numpy.reshape(modi_arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Question 3 Transpose and Flatten
import numpy

N,M=map(int,input().split(' '))
lis1=[]
for i in range(N):
    lis=list(map(int,input().split(' ')))
    lis1.extend(lis)
    #for j in range(N):
    #    lis1.append(int(input()))

modi_arr=numpy.array(lis1)

#numpy.reshape(modi_arr,(N,M))
modi_arr2=modi_arr.reshape(N,M)

print(numpy.transpose(modi_arr2))
print(modi_arr2.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [5]:
#Question 4 Concatenate
import numpy

N,M,P=map(int,input().split(' '))

np_arr22=[]
np_arr33=[]
for i in range(N):
    np_arr2=(list(map(int,input().split(' '))))
    np_arr22.append(np_arr2)
for i in range(M):
    np_arr3=(list(map(int,input().split(' '))))
    np_arr33.append(np_arr3)  

#np_arr22=numpy.array(np_arr22)
#np_arr33=numpy.array(np_arr33)

#np_arr22 = numpy.array([input().split() for _ in range(N)],int)
#np_arr33 = numpy.array([input().split() for _ in range(M)],int)

    
print(numpy.concatenate((np_arr22,np_arr33),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [6]:
#Question 5 Zeros and Ones
import numpy

lis=list(map(int,input().split()))

print (numpy.zeros((lis), dtype = numpy.int))
print (numpy.ones((lis), dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [7]:
#Question 6 Eye and Identity
import numpy

N,M=map(int,input().split())
numpy.set_printoptions(sign=' ')
#if(N==M):
#    print(str(numpy.identity(N).replace('1',' 1')).replace('0',' 0'))
#else:
print (numpy.eye(N,M, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [8]:
#Question 7 Array Mathematics
import numpy

N,M=map(int,input().split())
np_arr22=[]
np_arr33=[]
for i in range(N):
    np_arr2=(list(map(int,input().split(' '))))
    np_arr22.append(np_arr2)
for i in range(N):
    np_arr3=(list(map(int,input().split(' '))))
    np_arr33.append(np_arr3) 

a=numpy.array(np_arr22)
b=numpy.array(np_arr33)
#print (a + b)
print (numpy.add(a, b))        

#print (a - b)                    
print (numpy.subtract(a, b))     

#print a * b                     
print ( numpy.multiply(a, b))    

print (a // b)                     
#print (numpy.divide((a, b),dtype=int))
#print (numpy.floor_divide((a, b)))
#print a % b                     
print (numpy.mod(a, b))         

#print a**b                       
print (numpy.power(a, b))    

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [10]:
#Question 8 Floor, Ceil and Rint
import numpy

arr_lis=numpy.array(list(map(float,input().split())))
numpy.set_printoptions(sign=' ')
print(numpy.floor(arr_lis))
print(numpy.ceil(arr_lis))
print(numpy.rint(arr_lis))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [11]:
#Question 9 Sum and Prod
import numpy

lis1=[]
N,M=map(int,input().split())
for i in range(N):
    lis=list(map(int,input().split()))
    lis1.append(lis)
    
arr_lis=numpy.array(lis1)

ans1=(numpy.sum(arr_lis,axis=0))

print(numpy.prod(ans1,axis=None))
#print(numpy.prod(ans1))

2 2
1 2
3 4
24


In [12]:
#Question 10 Min and Max
import numpy

N,M=map(int,input().split())
lis1=[]
for i in range(N):
    lis=list(map(int,input().split()))
    lis1.append(lis)
    
arr_lis=numpy.array(lis1)
ans1=numpy.min(arr_lis,axis=1)
ans=numpy.max(ans1)
print(ans)

4 2
2 5
3 7
1 3
4 0
3


In [14]:
#Question 11 Mean, Var, and Std
import numpy

N,M=map(int,input().split())
lis1=[]
'''for i in range(N):
    lis=list(map(int,input().split()))
    lis1.append(lis)'''
    
lis1=numpy.array([input().strip().split() for i in range(N)],int)


arr_lis=numpy.array(lis1)
print(numpy.mean(arr_lis,axis=1))
print(numpy.var(arr_lis,axis=0))
print (round(numpy.std(arr_lis),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [15]:
#Question 12 Dot and Cross
import numpy

N=int(input())

A=numpy.array([input().split() for i in range(N)],int)    
B=numpy.array([input().split() for i in range(N)],int)

#print (numpy.dot(A, B))
#print (numpy.cross(A, B))
print(numpy.matmul(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [16]:
#Question 13 Inner and Outer
import numpy

A=numpy.array(input().split(),int)
B=numpy.array(input().split(),int)

print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [18]:
#Question 14 Polynomials
import numpy
'''
print (numpy.poly([-1, 1, 1, 10]))        #Output : [  1 -11   9  11 -10]
print (numpy.roots([1, 0, -1]))           #Output : [-1.  1.]
print (numpy.polyint([1, 1, 1])          #Output : [ 0.33333333  0.5         1.          0.        ]
print (numpy.polyder([1, 1, 1, 1]))       #Output : [3 2 1]
print (numpy.polyval([1, -2, 0, 2], 4))   #Output : 34
print (numpy.polyfit([0,1,-1, 2, -2], [0,1,1, 4, 4], 2))
  #Output : [  1.00000000e+00   0.00000000e+00  -3.97205465e-16]
#The functions polyadd, polysub, polymul, and polydiv also handle proper addition, #subtraction, multiplication, and division of polynomial coefficients, respectively.
'''
P=numpy.array(input().split(),float)
x=int(input())
print (numpy.polyval(P, x)  )


1.1 2 3
0
3.0


In [19]:
#Question 15  Linear Algebra
#https://numpy.org/doc/stable/reference/routines.linalg.html
import numpy

N=int(input())
A=numpy.array([input().split() for i in range(N)],float)
ans=numpy.linalg.det(A)
print(round(ans,2))

2
1.1 1.1
1.1 1.1
0.0
